# Generated by Django 2.1.5 on 2020-06-23 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20200520_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postss',
            options={'ordering': ['-PostDate']},
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postss',
            name='Videos_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
