# Generated by Django 2.1.5 on 2020-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20200623_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Profile_picture',
            field=models.FileField(blank=True, default='blah.jpg', upload_to=''),
        ),
    ]
