# Generated by Django 2.1.5 on 2019-07-31 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20190731_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 22, 16, 26, 969618)),
        ),
        migrations.AlterField(
            model_name='postss',
            name='Thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
