# Generated by Django 2.1.5 on 2019-07-31 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20190731_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 22, 44, 22, 25605)),
        ),
    ]
