# Generated by Django 2.1.5 on 2019-07-31 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 14, 34, 53, 928805)),
        ),
    ]
