# Generated by Django 2.1.5 on 2019-07-31 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190731_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default='Malcom2000@live.se', max_length=100),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 18, 17, 42, 850933)),
        ),
    ]
